---
- hosts: all
  tasks:
    - name: 'Instala pacotes de dependencia do sistema operaiconal'
      apt:
        name: "{{ item }}"
        state: latest
      become: yes
      with_items:
          - php7.2
          - apache2
          - libapache2-mod-php7.2
          - mysql-server-5.7
          - python-mysqldb
          - php7.2-mysql
